name: Build and Release

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [linux]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install

      - name: Build executable
        run: |
          npx pkg . --targets node18-${{ matrix.platform }}-x64 --output dist/app-${{ matrix.platform }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-${{ matrix.platform }}
          path: dist/app-${{ matrix.platform }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v3
        with:
          name: app-linux

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          files: |
            app-linux
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
